### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by spender-sandbox** [endgameinc/Maxwell#1]
As this seems to be using ancient cuckoomon code verbatim, has Endgame Inc. purchased a commercial license from upstream Cuckoo devs to be able to relicense the code as MIT?  It looks like the version that was copied might have been before cuckoomon added its GPLv3 license or any mention of copyright at all in the headers (as any copyright mention is missing from the files in the repo) but surely that wouldn't grant Endgame the ability to relicense that code under the MIT license.

-Brad

**Comment by dezhub** [comment]
Hello Brad, what part of code do you think is from cuckoomon?

Thanks, 
Joe

**Comment by spender-sandbox** [comment]
https://github.com/endgameinc/Maxwell/blob/master/flux/hook.h#L5
https://github.com/endgameinc/Maxwell/blob/master/flux/hook.h#L19
https://github.com/endgameinc/Maxwell/blob/master/flux/log.h#L12

etc etc

-Brad

**Comment by dezhub** [comment]
Hey Brad, thanks for bringing this to our attention. Changes have been made to the repo

**Comment by spender-sandbox** [comment]
For the record, renaming variables, expanding macros, and removing clearly copy+pasted comments is a slimy way to avoid copyright and credit (and such methodical translations likely don't count as creative expressions).  Despite upstream doing the same to me, I do need to point this out even though it's their code being ripped off in this case.

-Brad
